# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vinesF', '0003_video_lpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='LPath',
        ),
        migrations.AddField(
            model_name='video',
            name='VPath',
            field=models.FilePathField(default=datetime.datetime(2017, 12, 15, 14, 47, 41, 253000, tzinfo=utc), path='vinef/Videos'),
            preserve_default=False,
        ),
    ]
