# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinesF', '0005_remove_video_vpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='VPath',
            field=models.FilePathField(null=True, path=b'C:\\Users\\Roland\\eclipse-workspace\\vines\\src'),
        ),
    ]
