# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinesF', '0006_video_vpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='AddPath',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='VPath',
            field=models.FilePathField(null=True, path=b'C:\\Users\\Roland\\eclipse-workspace\\vines\\src\\vinesF/static/vinef/Videos'),
        ),
    ]
