# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 11:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('vinesF', '0007_auto_20171229_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Phone Number')),
                ('born_date', models.DateField(blank=True, default=None, null=True, verbose_name='Born date')),
                ('last_connexion', models.DateField(blank=True, default=None, null=True, verbose_name='Date Of Last Connexion')),
                ('years_seniority', models.IntegerField(default=0, verbose_name='Seniority')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='AddPath',
        ),
        migrations.RemoveField(
            model_name='video',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='VPath',
        ),
        migrations.AddField(
            model_name='video',
            name='file_path',
            field=models.FileField(default=datetime.datetime(2018, 5, 23, 11, 10, 11, 2000, tzinfo=utc), upload_to='videos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='Link',
            field=models.URLField(null=True),
        ),
    ]
