# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinesF', '0009_auto_20180605_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitbck2bck',
            old_name='Hit',
            new_name='Hitz',
        ),
    ]
