# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinesF', '0010_auto_20180605_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='minihit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinesF.video')),
            ],
        ),
    ]
