# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinesF', '0011_minihit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='PreferredAudience',
            field=models.CharField(choices=[('Gn', 'geneal'), ('Af', 'Africa'), ('ot', 'Others')], max_length=40),
        ),
    ]
