# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinesF', '0013_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='name',
        ),
    ]
