# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vinesF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MostViewes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinesF.viewcounter')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='LPath',
        ),
        migrations.AddField(
            model_name='latest',
            name='Added',
            field=models.ForeignKey(default=datetime.datetime(2017, 11, 27, 17, 30, 49, 23000, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='vinesF.video'),
            preserve_default=False,
        ),
    ]
